TRUNCATE TABLE "user" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "cinema" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "hall" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "seat" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "movie" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "showtime" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "booking" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "bookingSeat" RESTART IDENTITY CASCADE;